language: objective-c
osx_image: xcode8
xcode_project: ASMapLauncher.xcworkspace
xcode_scheme: ASMapLauncherTests
xcode_sdk: iphonesimulator9.3

branches:
 only:
 - master

script:
- xcodebuild -workspace ASMapLauncher.xcworkspace -scheme ASMapLauncher -destination "platform=iOS Simulator,name=iPhone 6,OS=9.0" clean test