language: swift

branches:
 only:
 - master

xcode_project: ASMapLauncher.xcodeproj
xcode_scheme: ASMapLauncherTests
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.0

script:
- xcodebuild clean build test -project ASMapLauncher.xcodeproj -scheme ASMapLauncherTests